name: E2E
on: push

env:
  GOPATH: /home/runner/go
  LUXPATH: src/github.com/luxfi
  ACTIONS_RUNTIME_URL:
  ACTIONS_RUNTIME_TOKEN:
  ACTIONS_CACHE_URL:

jobs:
  e2e:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout LuxJS
        uses: actions/checkout@v2
        with:
          repository: "luxfi/luxjs"
      - name: Install dependencies
        run: sudo apt update && sudo apt install zstd git build-essential nodejs -y
      - name: Install NodeJS dependencies
        run: yarn install --frozen-lockfile
      - name: Setup GoLang Version
        uses: actions/setup-go@v1
        with:
          go-version: 1.19.x
      - name: Setup GOPATH and LUXPATH
        run: |
          mkdir -p $GOPATH/$LUXPATH
      - name: Install autoremove
        run: sudo apt-get autoremove -y
      - name: Clone and Build Lux Node
        run: |
          cd $GOPATH/$LUXPATH
          git clone https://github.com/luxfi/node
          cd node
          ./scripts/build.sh
      - name: Checkout ANR
        run: |
          cd $GOPATH/$LUXPATH
          git clone https://github.com/luxfi/netrunner
      - name: Starting ANR
        run: |
          cd $GOPATH/$LUXPATH
          cd netrunner
          git checkout v1.0.12
          go run ./examples/local/fivenodenetwork/main.go &
      - name: LuxJS E2E Test
        env:
          LUXD_IP: localhost
          LUXD_PORT: 9650
        run: sleep 60 && yarn test -i --roots e2e_tests
